Repository scilus/nf-scil, pull requests merged in 2024-07, with the labels that each got.

#168 [FIX] Detached HEAD problem with nf-core commands
  .devcontainer/updateContentCommand.sh
Labels: bug

#181 [DOCS] Docs for creating tests with `nf-test`
  README.md
  docs/MODULE.md
  docs/SUBWORKFLOWS.md
Labels: documentation

#180 [Module] Add image/applymask module.
  modules/nf-scil/image/applymask/environment.yml
  modules/nf-scil/image/applymask/main.nf
  modules/nf-scil/image/applymask/meta.yml
  modules/nf-scil/image/applymask/tests/main.nf.test
  modules/nf-scil/image/applymask/tests/main.nf.test.snap
  modules/nf-scil/image/applymask/tests/tags.yml
Labels: assembly

#179 [Module] Add image/powderaverage module
  modules/nf-scil/image/powderaverage/environment.yml
  modules/nf-scil/image/powderaverage/main.nf
  modules/nf-scil/image/powderaverage/meta.yml
  modules/nf-scil/image/powderaverage/tests/main.nf.test
  modules/nf-scil/image/powderaverage/tests/main.nf.test.snap
  modules/nf-scil/image/powderaverage/tests/nextflow.config
  modules/nf-scil/image/powderaverage/tests/tags.yml
Labels: assembly
