Repository scilus/nf-scil, pull requests merged in 2024-05, with the labels that each got.

#137 Migrate denoising modules to scilpy 2.0.0 + nf-test.
  modules/nf-scil/denoising/mppca/environment.yml
  modules/nf-scil/denoising/mppca/main.nf
  modules/nf-scil/denoising/mppca/tests/main.nf.test
  modules/nf-scil/denoising/mppca/tests/main.nf.test.snap
  modules/nf-scil/denoising/mppca/tests/nextflow.config
  modules/nf-scil/denoising/mppca/tests/tags.yml
  modules/nf-scil/denoising/nlmeans/environment.yml
  modules/nf-scil/denoising/nlmeans/main.nf
  modules/nf-scil/denoising/nlmeans/tests/main.nf.test
  modules/nf-scil/denoising/nlmeans/tests/main.nf.test.snap
  modules/nf-scil/denoising/nlmeans/tests/nextflow.config
  modules/nf-scil/denoising/nlmeans/tests/tags.yml
  subworkflows/nf-scil/preproc_t1/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-scil/denoising/mppca/main.nf
  tests/modules/nf-scil/denoising/mppca/nextflow.config
  tests/modules/nf-scil/denoising/mppca/test.yml
  tests/modules/nf-scil/denoising/nlmeans/main.nf
  tests/modules/nf-scil/denoising/nlmeans/test.yml
Labels: enhancement

#146 [Subworkflow] BundleSeg subworkflow.
  modules/nf-scil/registration/ants/tests/main.nf.test.snap
  modules/nf-scil/registration/ants/tests/nextflow_quick.config
  subworkflows/nf-scil/bundle_seg/main.nf
  subworkflows/nf-scil/bundle_seg/meta.yml
  subworkflows/nf-scil/bundle_seg/tests/main.nf.test
  subworkflows/nf-scil/bundle_seg/tests/main.nf.test.snap
  subworkflows/nf-scil/bundle_seg/tests/nextflow.config
  subworkflows/nf-scil/bundle_seg/tests/tags.yml
  subworkflows/nf-scil/registration/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
Labels: assembly

#70 [Module] ihMT module
  modules/nf-scil/reconst/ihmt/environment.yml
  modules/nf-scil/reconst/ihmt/main.nf
  modules/nf-scil/reconst/ihmt/meta.yml
  modules/nf-scil/reconst/ihmt/tests/main.nf.test
  modules/nf-scil/reconst/ihmt/tests/main.nf.test.snap
  modules/nf-scil/reconst/ihmt/tests/nextflow.config
  modules/nf-scil/reconst/ihmt/tests/tags.yml
Labels: WIP, waiting

#153 [Module] Remove invalid streamlines module.
  modules/nf-scil/tractogram/removeinvalid/environment.yml
  modules/nf-scil/tractogram/removeinvalid/main.nf
  modules/nf-scil/tractogram/removeinvalid/meta.yml
  modules/nf-scil/tractogram/removeinvalid/tests/main.nf.test
  modules/nf-scil/tractogram/removeinvalid/tests/main.nf.test.snap
  modules/nf-scil/tractogram/removeinvalid/tests/nextflow.config
  modules/nf-scil/tractogram/removeinvalid/tests/tags.yml
Labels: assembly

#154 [Module] Compute centroids module.
  modules/nf-scil/bundle/centroid/environment.yml
  modules/nf-scil/bundle/centroid/main.nf
  modules/nf-scil/bundle/centroid/meta.yml
  modules/nf-scil/bundle/centroid/tests/main.nf.test
  modules/nf-scil/bundle/centroid/tests/main.nf.test.snap
  modules/nf-scil/bundle/centroid/tests/nextflow.config
  modules/nf-scil/bundle/centroid/tests/tags.yml
Labels: assembly

#157 [Module] Resample tractogram module.
  modules/nf-scil/tractogram/resample/environment.yml
  modules/nf-scil/tractogram/resample/main.nf
  modules/nf-scil/tractogram/resample/meta.yml
  modules/nf-scil/tractogram/resample/tests/main.nf.test
  modules/nf-scil/tractogram/resample/tests/main.nf.test.snap
  modules/nf-scil/tractogram/resample/tests/nextflow_centroid.config
  modules/nf-scil/tractogram/resample/tests/nextflow_tractogram.config
  modules/nf-scil/tractogram/resample/tests/tags.yml
Labels: assembly

#158 [Module] Label Map module.
  modules/nf-scil/bundle/labelmap/environment.yml
  modules/nf-scil/bundle/labelmap/main.nf
  modules/nf-scil/bundle/labelmap/meta.yml
  modules/nf-scil/bundle/labelmap/tests/main.nf.test
  modules/nf-scil/bundle/labelmap/tests/main.nf.test.snap
  modules/nf-scil/bundle/labelmap/tests/nextflow.config
  modules/nf-scil/bundle/labelmap/tests/tags.yml
Labels: assembly
